"""update exam model

Revision ID: cbd541f38194
Revises: e2aa25397d37
Create Date: 2026-07-25 16:26:38.639390

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbd541f38194'
down_revision: Union[str, Sequence[str], None] = 'e2aa25397d37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('duration_minutes', sa.Integer(), nullable=False))
    op.add_column('exams', sa.Column('pass_marks', sa.Integer(), nullable=False))
    op.add_column('exams', sa.Column('shuffle_questions', sa.Boolean(), nullable=False))
    op.add_column('exams', sa.Column('shuffle_options', sa.Boolean(), nullable=False))
    op.add_column('exams', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('exams', 'randomize_questions')
    op.drop_column('exams', 'duration')
    op.drop_column('exams', 'question_count')
    op.drop_column('exams', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exams', sa.Column('status', postgresql.ENUM('DRAFT', 'PUBLISHED', 'COMPLETED', name='examstatus'), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('question_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('exams', sa.Column('randomize_questions', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('exams', 'is_active')
    op.drop_column('exams', 'shuffle_options')
    op.drop_column('exams', 'shuffle_questions')
    op.drop_column('exams', 'pass_marks')
    op.drop_column('exams', 'duration_minutes')
    # ### end Alembic commands ###
