"""add proctor_events_table

Revision ID: ce6d80fac124
Revises: cbd541f38194
Create Date: 2026-07-26 17:17:26.710310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ce6d80fac124'
down_revision: Union[str, Sequence[str], None] = 'cbd541f38194'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('proctor_events', 'event_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_index(op.f('ix_proctor_events_event_type'), 'proctor_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_proctor_events_exam_session_id'), 'proctor_events', ['exam_session_id'], unique=False)
    op.drop_constraint(op.f('proctor_events_exam_session_id_fkey'), 'proctor_events', type_='foreignkey')
    op.create_foreign_key(None, 'proctor_events', 'exam_sessions', ['exam_session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'proctor_events', type_='foreignkey')
    op.create_foreign_key(op.f('proctor_events_exam_session_id_fkey'), 'proctor_events', 'exam_sessions', ['exam_session_id'], ['id'])
    op.drop_index(op.f('ix_proctor_events_exam_session_id'), table_name='proctor_events')
    op.drop_index(op.f('ix_proctor_events_event_type'), table_name='proctor_events')
    op.alter_column('proctor_events', 'event_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
