"""add feedback to answers

Revision ID: d0344f277764
Revises: ce6d80fac124
Create Date: 2026-07-26 17:55:48.587279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0344f277764'
down_revision: Union[str, Sequence[str], None] = 'ce6d80fac124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('feedback', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answers', 'feedback')
    # ### end Alembic commands ###
