"""add email verification fields

Revision ID: de7974bd89fe
Revises: d0344f277764
Create Date: 2026-10-06 14:29:59.401569

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de7974bd89fe'
down_revision: Union[str, Sequence[str], None] = 'd0344f277764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_token', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('verification_token_expires_at', sa.DateTime(), nullable=True))
    op.create_unique_constraint(None, 'users', ['verification_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'verification_token_expires_at')
    op.drop_column('users', 'verification_token')
    # ### end Alembic commands ###
