"""update question bank model

Revision ID: e2aa25397d37
Revises: 5652c589ab60
Create Date: 2026-07-24 22:54:44.176944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2aa25397d37'
down_revision: Union[str, Sequence[str], None] = '5652c589ab60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_answer_option', 'answer_options', ['answer_id', 'option_id'])
    op.add_column('question_bank', sa.Column('subject', sa.String(length=100), nullable=False))
    op.add_column('question_bank', sa.Column('topic', sa.String(length=100), nullable=True))
    op.add_column('question_bank', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('question_bank', sa.Column('language', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_question_bank_created_by'), 'question_bank', ['created_by'], unique=False)
    op.create_index(op.f('ix_question_bank_difficulty'), 'question_bank', ['difficulty'], unique=False)
    op.create_index(op.f('ix_question_bank_question_type'), 'question_bank', ['question_type'], unique=False)
    op.create_index(op.f('ix_question_bank_subject'), 'question_bank', ['subject'], unique=False)
    op.create_index(op.f('ix_question_bank_topic'), 'question_bank', ['topic'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_bank_topic'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_subject'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_question_type'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_difficulty'), table_name='question_bank')
    op.drop_index(op.f('ix_question_bank_created_by'), table_name='question_bank')
    op.drop_column('question_bank', 'language')
    op.drop_column('question_bank', 'is_active')
    op.drop_column('question_bank', 'topic')
    op.drop_column('question_bank', 'subject')
    op.drop_constraint('uq_answer_option', 'answer_options', type_='unique')
    # ### end Alembic commands ###
